name: Build VST3 Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Plugin
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: AudioLabPro-Plugin-Windows
        # Questo percorso è quello esatto che abbiamo visto nei log del tuo errore precedente
        path: build/AudioLabPro_artefacts/Release/VST3/AudioLabPro.vst3
