name: Build VST3 Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4 # Aggiornato a v4
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Plugin
      run: cmake --build build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Aggiornato a v4 per risolvere l'errore dello screenshot
      with:
        name: AudioLabPro-Plugin-Windows
        path: build/AudioLabPro_artefacts/Release/VST3/AudioLabPro.vst3
